# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Run test suite (all default simulators)"
  lane :tests do
    scan(
      devices: ["iPhone 17", "iPhone 17 Pro", "iPad (A16)"],
      deployment_target_version: "26.2"
    )
  end
end
