# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # ------ Continuous Integration ------

  desc "Run test suite on iPhone 17"
  lane :tests_iphone17 do
    # See Scanfile for default configuration
    scan(
      devices: ["iPhone 17"],
      deployment_target_version: "26.2"
    )
  end

  desc "Run test suite on iPhone 17 Pro"
  lane :tests_iphone17pro do
    # See Scanfile for default configuration
    scan(
      devices: ["iPhone 17 Pro"],
      deployment_target_version: "26.2"
    )
  end

  desc "Run test suite on iPad (A16)"
  lane :tests_ipad do
    # See Scanfile for default configuration
    scan(
      devices: ["iPad (A16)"],
      deployment_target_version: "26.2"
    )
  end

  desc "Run test suite (all default simulators)"
  lane :tests do
    scan()
  end

  # ------ Continuous Delivery ------

  desc "Set up keychain access for Match usage"
  lane :CD_setup_keychain do
    if is_ci
      # Caution: take care with the default_keychain parameter
      create_keychain(
        default_keychain: "true",
        name: "bikeindex_keychain",
        password: "bikeindex_keychain_password_2026",
        unlock: true,
        timeout: "3600",
        lock_when_sleeps: false
      )
    else
      puts "Failed to run CD_setup_keychain, is_ci value is false. Please set up keychain with fastlane run create_keychain"
    end
  end

  desc "Perform all tasks to make a new release: increment build, archive, upload"
  lane :BI_build_release_archive do
    current_build_number = latest_testflight_build_number(
      # Only available for CI/CD after "Load API key" step
      api_key_path: "./fastlane/api-key.json"
    )

    increment_build_number({
      build_number: current_build_number + 1,
    })

    gym()

    deliver(
      # Only available for CI/CD after "Load API key" step
      api_key_path: "./fastlane/api-key.json",
      skip_screenshots: true,
      skip_metadata: true,
      precheck_include_in_app_purchases: false,
      copyright: "2025 © Bike Index, a 501(c)(3) nonprofit - EIN 81-4296194"
    )
  end
end
