# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

# frozen_string_literal: true

scheme("BikeIndex")

# Where should the resulting screenshots be stored?
# Shared by fastlane snapshot and deliver (screenshot_paths default)
output_directory("./screenshots")

devices([
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPad Air 13-inch (M4)",
  "iPad Air 11-inch (M4)",
])

concurrent_simulators(false)

# Essential test plan
testplan("ReleaseScreenshots")
